name: cloud_store
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  archive: ^3.3.7
  cloud_firestore: ^4.8.2
  file_picker: ^5.3.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.3
  flutter:
    sdk: flutter
  http: ^1.1.0
  http_parser: ^4.0.2
  mime: ^1.0.4
  open_file: ^3.3.2
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
