// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'firebase_options.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDM2Aci3eAlNQjfHteHwcbC8I0xoi8Ad-s',
    appId: '1:405177365694:web:d50296dd18ea6c5dce1aef',
    messagingSenderId: '405177365694',
    projectId: 'cloudstore-4361c',
    authDomain: 'cloudstore-4361c.firebaseapp.com',
    storageBucket: 'cloudstore-4361c.appspot.com',
    measurementId: 'G-9P6DNTRTXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JeqadcIoW4EmICUMbwpNVRTMrwruwfY',
    appId: '1:405177365694:android:80733d05f436c8face1aef',
    messagingSenderId: '405177365694',
    projectId: 'cloudstore-4361c',
    storageBucket: 'cloudstore-4361c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIiUlhS-mKf-sGm3R2HfLKxN5P9AyBfA0',
    appId: '1:405177365694:ios:e0f407c0184e409fce1aef',
    messagingSenderId: '405177365694',
    projectId: 'cloudstore-4361c',
    storageBucket: 'cloudstore-4361c.appspot.com',
    iosClientId:
        '405177365694-2icn3vs9ssg8m0cmn8i0hr0qvcj5nl7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIiUlhS-mKf-sGm3R2HfLKxN5P9AyBfA0',
    appId: '1:405177365694:ios:cae6615d74e38131ce1aef',
    messagingSenderId: '405177365694',
    projectId: 'cloudstore-4361c',
    storageBucket: 'cloudstore-4361c.appspot.com',
    iosClientId:
        '405177365694-ds0gp1sti9ppr4l47jmabej93fdcg8oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.cloudStore.RunnerTests',
  );
}
